name: hierhgt-dti
channels:
  - pytorch
  - nvidia
  - pyg
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.1.*
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - dgl
  - pyg::pytorch-scatter
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - rdkit
  - tqdm
  - pyyaml
  - networkx
  - pip
  - pip:
      - dgllife
      - fair-esm
      - prettytable
